import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-latte.toml"
]

[colors.primary]
# background = "#262a32"

[env]
TERM = "xterm-256color"

[font]
size = 15

[font.normal]
family = "Hack Nerd Font"

[font.offset]
y = 2

[window]
decorations = "full"
opacity = 0.9
startup_mode = "Fullscreen"
